# Generated by Django 6.0.4 on 2026-05-01 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_band_like_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='like_new',
        ),
    ]
